### PR TITLE
Dockerized and Refactored the model

### PR DESCRIPTION
**Pull request by samuelmaina**

### CODE REVIEW

**Comment by samuelmaina** [comment]
HI @GemmaTuron ,
Can you have a look at this PR.

**Comment by GemmaTuron** [comment]
@samuelmaina 
I think it all looks good but could you eliminate the mock.csv file and the .DS_STORE (legacy from pushing from a Mac) files?
Also the Mock csv is the only git lfs tracked object, so this could be deleted

**Comment by samuelmaina** [comment]
Hi @GemmaTuron , 
The model failed due to the ersilia intallation  problem. When you solve the issue, this model is affected.

**Comment by samuelmaina** [comment]
Hi @GemmaTuron ,
I will also update the workflows for this.

**Comment by GemmaTuron** [comment]
Hi @samuelmaina 

The workflows are updated already, I have assigned model testing ;)

**Pull request merged**
